CLASS zcx_i_a2cc_metrics_impl_error DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC INHERITING FROM cx_static_check.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_i_a2cc_metrics_impl_error IMPLEMENTATION.
ENDCLASS.
